# UK Healthcare Spending Trends & Funding Structure Analysis – Data Cleaning

## Project Overview
This notebook documents the data cleaning and preparation process for the **UK Healthcare Spending Trends & Funding Structure Analysis** project.

The dataset was sourced from the **Office for National Statistics (ONS)** and contains historical UK healthcare expenditure data from **1997 to 2012**, including:

- Total healthcare expenditure
- Public sector healthcare expenditure
- Private sector healthcare expenditure
- Revision values

## Objective
The purpose of this notebook is to clean and structure the raw dataset so it can be used for:

- exploratory data analysis
- SQL-based analysis
- Power BI dashboard development

## Data Cleaning Tasks
The notebook performs the following steps:

1. Load the raw Excel dataset
2. Identify and extract the relevant table
3. Rename and standardise columns
4. Convert values to numeric format
5. Create derived analytical fields such as:
   - Public funding share (%)
   - Private funding share (%)
   - Year-on-year growth (%)
6. Export the cleaned dataset for downstream analysis

## Tools Used
- Python
- Pandas
- NumPy

In [112]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [113]:
import pandas as pd
import numpy as np

In [114]:
file_path = "referencetable10revisionstototalpublicsectorandprivatesectorhealthcareexpenditureintheuk19972012_tcm77-399797.xls"

df_raw = pd.read_excel(file_path, sheet_name=0, header=None, engine="xlrd")
df_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,2015.0,2014.0,Revision,NaN,2015.0,2014.0,Revision,NaN,2015.0,2014.0,Revision
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997.0,54.9,54.6,0.3,NaN,44.1,43.9,0.2,NaN,10.8,10.7,0.1
3,1998.0,58.6,58.3,0.3,NaN,47.1,46.8,0.2,NaN,11.5,11.4,0.1
4,1999.0,64.1,63.7,0.3,NaN,51.6,51.4,0.2,NaN,12.4,12.4,0.1
5,2000.0,68.5,68.2,0.3,NaN,54.5,54.2,0.3,NaN,14.0,14.0,0
6,2001.0,75.4,74.3,1.1,NaN,59.5,59.1,0.4,NaN,15.9,15.2,0.7
7,2002.0,81.8,81.4,0.5,NaN,65.3,64.8,0.5,NaN,16.5,16.5,0
8,2003.0,89.7,89.3,0.4,NaN,71.3,70.8,0.5,NaN,18.4,18.5,-0.1
9,2004.0,96.8,96.0,0.8,NaN,78.6,78.1,0.6,NaN,18.2,17.9,0.3
10,2005.0,105.1,103.8,1.4,NaN,85.0,84.4,0.6,NaN,20.1,19.4,0.7
11,2006.0,112.9,111.8,1,NaN,92.1,91.4,0.7,NaN,20.7,20.5,0.3
12,2007.0,120.2,119.5,0.6,NaN,97.0,96.2,0.8,NaN,23.2,23.3,-0.1
13,2008.0,129.4,128.4,1,NaN,105.6,104.6,1,NaN,23.8,23.8,0
14,2009.0,139.0,137.9,1.1,NaN,115.7,114.7,1,NaN,23.3,23.2,0.1

In [115]:
print("Raw shape:", df_raw.shape)

Raw shape: (18, 12)

In [116]:
df = df_raw.copy()

# keep rows where first column looks like a year
df = df[df[0].apply(lambda x: isinstance(x, (int, float)) and 1900 <= x <= 2100)]

df.head()

       0     1     2    3   4     5     6    7   8     9     10   11
2  1997.0  54.9  54.6  0.3 NaN  44.1  43.9  0.2 NaN  10.8  10.7  0.1
3  1998.0  58.6  58.3  0.3 NaN  47.1  46.8  0.2 NaN  11.5  11.4  0.1
4  1999.0  64.1  63.7  0.3 NaN  51.6  51.4  0.2 NaN  12.4  12.4  0.1
5  2000.0  68.5  68.2  0.3 NaN  54.5  54.2  0.3 NaN  14.0  14.0    0
6  2001.0  75.4  74.3  1.1 NaN  59.5  59.1  0.4 NaN  15.9  15.2  0.7

In [117]:
df = df[[0, 1, 2, 3, 5, 6, 7, 9,10,11]].copy()
df.head()

       0     1     2    3     5     6    7     9     10   11
2  1997.0  54.9  54.6  0.3  44.1  43.9  0.2  10.8  10.7  0.1
3  1998.0  58.6  58.3  0.3  47.1  46.8  0.2  11.5  11.4  0.1
4  1999.0  64.1  63.7  0.3  51.6  51.4  0.2  12.4  12.4  0.1
5  2000.0  68.5  68.2  0.3  54.5  54.2  0.3  14.0  14.0    0
6  2001.0  75.4  74.3  1.1  59.5  59.1  0.4  15.9  15.2  0.7

In [118]:
df.columns = [
    "year",
    "total_2015",
    "total_2014",
    "total_revision",
    "public_2015",
    "public_2014",
    "public_revision",
    "private_2015",
    "private_2014",
    "private_revision"
]

df.head()

,year,total_2015,total_2014,total_revision,public_2015,public_2014,public_revision,private_2015,private_2014,private_revision
2,1997.0,54.9,54.6,0.3,44.1,43.9,0.2,10.8,10.7,0.1
3,1998.0,58.6,58.3,0.3,47.1,46.8,0.2,11.5,11.4,0.1
4,1999.0,64.1,63.7,0.3,51.6,51.4,0.2,12.4,12.4,0.1
5,2000.0,68.5,68.2,0.3,54.5,54.2,0.3,14.0,14.0,0
6,2001.0,75.4,74.3,1.1,59.5,59.1,0.4,15.9,15.2,0.7

In [119]:
df

,year,total_2015,total_2014,total_revision,public_2015,public_2014,public_revision,private_2015,private_2014,private_revision
2,1997.0,54.9,54.6,0.3,44.1,43.9,0.2,10.8,10.7,0.1
3,1998.0,58.6,58.3,0.3,47.1,46.8,0.2,11.5,11.4,0.1
4,1999.0,64.1,63.7,0.3,51.6,51.4,0.2,12.4,12.4,0.1
5,2000.0,68.5,68.2,0.3,54.5,54.2,0.3,14.0,14.0,0
6,2001.0,75.4,74.3,1.1,59.5,59.1,0.4,15.9,15.2,0.7
7,2002.0,81.8,81.4,0.5,65.3,64.8,0.5,16.5,16.5,0
8,2003.0,89.7,89.3,0.4,71.3,70.8,0.5,18.4,18.5,-0.1
9,2004.0,96.8,96.0,0.8,78.6,78.1,0.6,18.2,17.9,0.3
10,2005.0,105.1,103.8,1.4,85.0,84.4,0.6,20.1,19.4,0.7
11,2006.0,112.9,111.8,1,92.1,91.4,0.7,20.7,20.5,0.3
12,2007.0,120.2,119.5,0.6,97.0,96.2,0.8,23.2,23.3,-0.1
13,2008.0,129.4,128.4,1,105.6,104.6,1,23.8,23.8,0
14,2009.0,139.0,137.9,1.1,115.7,114.7,1,23.3,23.2,0.1
15,2010.0,141.2,139.3,2,118.0,116.9,1.1,23.3,22.3,0.9
16,2011.0,143.5,141.9,1.7,119.3,118.4,1,24.2,23.5,0.7
17,2012.0,146.7,144.5,2.2,121.6,121.3,0.3,25.1,23.2,1.9

In [120]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 2 to 17
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              16 non-null     float64
 1   total_2015        16 non-null     float64
 2   total_2014        16 non-null     float64
 3   total_revision    16 non-null     float64
 4   public_2015       16 non-null     float64
 5   public_2014       16 non-null     float64
 6   public_revision   16 non-null     float64
 7   private_2015      16 non-null     float64
 8   private_2014      16 non-null     float64
 9   private_revision  16 non-null     float64
dtypes: float64(10)
memory usage: 1.9 KB

In [121]:
df = df.sort_values("year").reset_index(drop=True)
df.head()

,year,total_2015,total_2014,total_revision,public_2015,public_2014,public_revision,private_2015,private_2014,private_revision
0,1997.0,54.9,54.6,0.3,44.1,43.9,0.2,10.8,10.7,0.1
1,1998.0,58.6,58.3,0.3,47.1,46.8,0.2,11.5,11.4,0.1
2,1999.0,64.1,63.7,0.3,51.6,51.4,0.2,12.4,12.4,0.1
3,2000.0,68.5,68.2,0.3,54.5,54.2,0.3,14.0,14.0,0.0
4,2001.0,75.4,74.3,1.1,59.5,59.1,0.4,15.9,15.2,0.7

In [122]:
df["public_share_pct_2015"] = (df["public_2015"] / df["total_2015"]) * 100
df["private_share_pct_2015"] = (df["private_2015"] / df["total_2015"]) * 100

df["total_yoy_growth_pct_2015"] = df["total_2015"].pct_change() * 100
df["public_yoy_growth_pct_2015"] = df["public_2015"].pct_change() * 100
df["private_yoy_growth_pct_2015"] = df["private_2015"].pct_change() * 100

In [123]:
df["total_yoy_growth_pct_2015"] = df["total_yoy_growth_pct_2015"].fillna(0)
df["public_yoy_growth_pct_2015"] = df["public_yoy_growth_pct_2015"].fillna(0)
df["private_yoy_growth_pct_2015"] = df["private_yoy_growth_pct_2015"].fillna(0)

The first year (1997) has no previous year available for comparison, so the year-on-year growth calculation returns NaN. This missing value was replaced with 0 to maintain a complete dataset and ensure consistency for further analysis in SQL and Power BI.

In [124]:
df = df.round(2)
df.head()

,year,total_2015,total_2014,total_revision,public_2015,public_2014,public_revision,private_2015,private_2014,private_revision,public_share_pct_2015,private_share_pct_2015,total_yoy_growth_pct_2015,public_yoy_growth_pct_2015,private_yoy_growth_pct_2015
0,1997.0,54.9,54.6,0.3,44.1,43.9,0.2,10.8,10.7,0.1,80.33,19.67,0.00,0.00,0.00
1,1998.0,58.6,58.3,0.3,47.1,46.8,0.2,11.5,11.4,0.1,80.38,19.62,6.74,6.80,6.48
2,1999.0,64.1,63.7,0.3,51.6,51.4,0.2,12.4,12.4,0.1,80.50,19.34,9.39,9.55,7.83
3,2000.0,68.5,68.2,0.3,54.5,54.2,0.3,14.0,14.0,0.0,79.56,20.44,6.86,5.62,12.90
4,2001.0,75.4,74.3,1.1,59.5,59.1,0.4,15.9,15.2,0.7,78.91,21.09,10.07,9.17,13.57

In [125]:
latest_year = df["year"].max()
latest_total = df.loc[df["year"] == latest_year, "total_2015"].values[0]
latest_public_share = df.loc[df["year"] == latest_year, "public_share_pct_2015"].values[0]
highest_growth = df["total_yoy_growth_pct_2015"].max()
highest_growth_year = df.loc[df["total_yoy_growth_pct_2015"] == highest_growth, "year"].values[0]

print("Latest year:", latest_year)
print("Latest healthcare spend (£bn):", latest_total)
print("Public funding share in latest year (%):", latest_public_share)
print("Highest YoY growth (%):", highest_growth)
print("Highest growth year:", highest_growth_year)

Latest year: 2012.0
Latest healthcare spend (£bn): 146.7
Public funding share in latest year (%): 82.89
Highest YoY growth (%): 10.07
Highest growth year: 2001.0

In [126]:
df

,year,total_2015,total_2014,total_revision,public_2015,public_2014,public_revision,private_2015,private_2014,private_revision,public_share_pct_2015,private_share_pct_2015,total_yoy_growth_pct_2015,public_yoy_growth_pct_2015,private_yoy_growth_pct_2015
0,1997.0,54.9,54.6,0.3,44.1,43.9,0.2,10.8,10.7,0.1,80.33,19.67,0.00,0.00,0.00
1,1998.0,58.6,58.3,0.3,47.1,46.8,0.2,11.5,11.4,0.1,80.38,19.62,6.74,6.80,6.48
2,1999.0,64.1,63.7,0.3,51.6,51.4,0.2,12.4,12.4,0.1,80.50,19.34,9.39,9.55,7.83
3,2000.0,68.5,68.2,0.3,54.5,54.2,0.3,14.0,14.0,0.0,79.56,20.44,6.86,5.62,12.90
4,2001.0,75.4,74.3,1.1,59.5,59.1,0.4,15.9,15.2,0.7,78.91,21.09,10.07,9.17,13.57
5,2002.0,81.8,81.4,0.5,65.3,64.8,0.5,16.5,16.5,0.0,79.83,20.17,8.49,9.75,3.77
6,2003.0,89.7,89.3,0.4,71.3,70.8,0.5,18.4,18.5,-0.1,79.49,20.51,9.66,9.19,11.52
7,2004.0,96.8,96.0,0.8,78.6,78.1,0.6,18.2,17.9,0.3,81.20,18.80,7.92,10.24,-1.09
8,2005.0,105.1,103.8,1.4,85.0,84.4,0.6,20.1,19.4,0.7,80.88,19.12,8.57,8.14,10.44
9,2006.0,112.9,111.8,1.0,92.1,91.4,0.7,20.7,20.5,0.3,81.58,18.33,7.42,8.35,2.99
10,2007.0,120.2,119.5,0.6,97.0,96.2,0.8,23.2,23.3,-0.1,80.70,19.30,6.47,5.32,12.08
11,2008.0,129.4,128.4,1.0,105.6,104.6,1.0,23.8,23.8,0.0,81.61,18.39,7.65,8.87,2.59
12,2009.0,139.0,137.9,1.1,115.7,114.7,1.0,23.3,23.2,0.1,83.24,16.76,7.42,9.56,-2.10
13,2010.0,141.2,139.3,2.0,118.0,116.9,1.1,23.3,22.3,0.9,83.57,16.50,1.58,1.99,0.00
14,2011.0,143.5,141.9,1.7,119.3,118.4,1.0,24.2,23.5,0.7,83.14,16.86,1.63,1.10,3.86
15,2012.0,146.7,144.5,2.2,121.6,121.3,0.3,25.1,23.2,1.9,82.89,17.11,2.23,1.93,3.72

In [127]:
df.to_csv("cleaned_healthcare_expenditure.csv", index=False)
df.to_excel("cleaned_healthcare_expenditure.xlsx", index=False)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

## Conclusion

The original ONS healthcare expenditure dataset was successfully cleaned and transformed into a structured analytical dataset.

The final dataset includes:
- public and private funding share percentages
- year-on-year growth rates
- validated expenditure values

This cleaned dataset is ready for:
- SQL analysis
- Power BI dashboard development
- further business and financial analysis